name: Build Windows EXE
on:
  workflow_dispatch:        # 手动运行按钮
  push:
    branches: [ main ]      # 提交到 main 也会触发（备用）

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 不使用任何 cache 字段——避免“缺少锁文件”的报错
      - name: Setup Node (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Show Node & npm
        run: |
          node -v
          npm -v

      # 防呆：缺少 dist/index.html 时自动补一个占位页
      - name: Ensure dist/index.html exists (auto-fix)
        shell: pwsh
        run: |
          if (-not (Test-Path "dist")) { New-Item -ItemType Directory dist | Out-Null }
          if (-not (Test-Path "dist/index.html")) {
            @"
<!doctype html><meta charset="utf-8"><title>Placeholder</title><body>OK</body>
"@ | Set-Content -Encoding UTF8 dist/index.html
          }

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build Windows EXE (x64)
        run: npx electron-builder --win nsis portable --x64 --publish=never
        env:
          ELECTRON_CACHE: ${{ runner.temp }}\electron
          ELECTRON_BUILDER_CACHE: ${{ runner.temp }}\electron-builder

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cfa-windows-build
          path: |
            release\*.exe
            release\*.portable.exe
          if-no-files-found: error
