name: Build Windows EXE
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Build Windows EXE (x64)
        run: npx electron-builder --win nsis portable --x64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cfa-windows-build
          path: |
            release\*.exe
            release\*.portable.exe
          if-no-files-found: warn
